sudo: false
language: cpp
cache: apt

git:
  depth: 1

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - kalakris-cmake
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - libtool
    - gcc-4.8
    - g++-4.8
    - clang-3.4
    - make
    - cmake

install:
  - mkdir bin
  - cd bin
  - cmake ../ -DCMAKE_BUILD_TYPE=Release

script:
  - $CXX --version
  - make -j 4
  - ./TaskSchedulerTests
